version: '3'

services:
  db:
    image: postgres:14-alpine
    env_file: "../../.env"
    environment:
      POSTGRES_DB: ${DB_NAME:-files}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1111}
      POSTGRES_PORT: ${DB_PORT:-5432}
    volumes:
      - ../../postgres-data:/var/lib/postgresql/
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
  app:
    build:
      context: ../../
      dockerfile: deploy/dev/Dockerfile
    command: >
      bash -c "deploy/dev/scripts/wait-for-it.sh db:${DB_PORT:-5432} && \
               alembic upgrade head && \
               echo ${APP_PORT} && \
               uvicorn src.main:app --host=${APP_HOST:-0.0.0.0} --port=${APP_PORT:-8000} --proxy-headers --reload"
    env_file:
      - ../../.env
    environment:
      DSN__DB: postgresql+asyncpg://admin:1111@db:5432/files
    depends_on:
      - db
    ports:
      - ${APP_PORT:-8000}:${APP_PORT:-8000}
    volumes:
      - ../../media:/app/media
      - ../../:/app/

volumes:
  db:
  app:
